service: sales-order


frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  timeout: 30
  environment:
    MONGO_URI: ${env:MONGO_URI}




functions:

  configure:
    handler: src/controller/configure.configure
    events:
      - http:
          path: /webhooks
          method: get

  receivedmsg:
    handler: src/controller/receivedmsg.receivedmsg
    events:
      - http:
          path: /webhooks
          method: post
  savedata:
    handler: src/controller/data.savedata
    events:
      - http:
          path: /upload
          method: get

  

  